
alang=%13%ru,rus,en,eng
auto-window-resize=%2%no
autofit=%9%100%x100%
border=%2%no
force-window-position=%0%
image-display-duration=%3%inf
keep-open=%3%yes
loop-playlist=%0%
osd-bar=%2%no
prefetch-playlist=%0%
reset-on-next-file=%31%video-rotate,video-zoom,panscan
slang=%13%ru,rus,en,eng
sub-auto=%3%all
vo=%8%gpu-next

[fullscreen]
fullscreen=%0%
profile-cond=%47%video_unscaled or video_zoom > 0 or panscan > 0
profile-restore=%4%copy

[image]
linear-downscaling=%2%no
osc=%2%no
profile-cond=%113%p['current-tracks/video/image'] and not p['current-tracks/video/albumart'] and mp.command('enable-section image')
profile-restore=%4%copy

[loop-short]
loop-file=%0%
profile-cond=%98%duration < 30 and p['current-tracks/video/image'] == false and image_display_duration == math.huge

[video]
profile-cond=%80%p['current-tracks/video/image'] == false and mp.command('disable-section image')
profile-restore=%4%copy

