( {image} add video-zoom +.05
- {image} add video-zoom -.25
0 {image} no-osd set video-zoom 0; no-osd set panscan 0
9 {image} add video-zoom +.25
Alt+g script-message-to console type 'set playlist-pos-1 ; keypress ESC' 20
Ctrl+< {image} repeatable playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev; playlist-prev
Ctrl+> {image} repeatable playlist-next; playlist-next; playlist-next; playlist-next; playlist-next; playlist-next; playlist-next; playlist-next; playlist-next; playlist-next
Ctrl+DOWN {image} no-osd set video-align-y 1
Ctrl+LEFT {image} no-osd set video-align-x -1
Ctrl+RIGHT {image} no-osd set video-align-x 1
Ctrl+SPACE {image} repeatable playlist-prev force
Ctrl+UP {image} no-osd set video-align-y -1
Ctrl+WHEEL_DOWN {image} script-message cursor-centric-zoom -.1
Ctrl+WHEEL_UP {image} script-message cursor-centric-zoom .1
Ctrl+g playlist-play-index 0
Ctrl+h {image} no-osd set video-align-x -1
Ctrl+j {image} no-osd set video-align-y 1
Ctrl+k {image} no-osd set video-align-y -1
Ctrl+l {image} no-osd set video-align-x 1
Ctrl+r {image} playlist-shuffle; playlist-next; playlist-unshuffle
DOWN {image} repeatable script-message pan-image y +.2
G no-osd set playlist-pos-1 ${playlist-count}
H {image} repeatable script-message pan-image x -.02
J {image} repeatable script-message pan-image y +.02
K {image} repeatable script-message pan-image y -.02
L {image} repeatable script-message pan-image x +.02
LEFT {image} repeatable script-message pan-image x -.2
MBTN_LEFT {image} script-binding gesture
MBTN_LEFT_DBL {image} ignore
MBTN_MID {image} script-binding align-to-cursor
MBTN_RIGHT {image} script-binding drag-to-pan
RIGHT {image} repeatable script-message pan-image x +.2
SPACE {image} repeatable playlist-next force
Shift+DOWN {image} repeatable script-message pan-image y +.02
Shift+LEFT {image} repeatable script-message pan-image x -.02
Shift+RIGHT {image} repeatable script-message pan-image x +.02
Shift+UP {image} repeatable script-message pan-image y -.02
UP {image} repeatable script-message pan-image y -.2
WHEEL_DOWN {image} script-message pan-image y .05
WHEEL_LEFT {image} script-message pan-image x -.05
WHEEL_RIGHT {image} script-message pan-image x .05
WHEEL_UP {image} script-message pan-image y -.05
_ {image} add video-zoom -.05
d {image} script-message double-page-mode
h {image} repeatable script-message pan-image x -.2
j {image} repeatable script-message pan-image y +.2
k {image} repeatable script-message pan-image y -.2
l {image} repeatable script-message pan-image x +.2
o {image} no-osd set panscan 1; no-osd set video-unscaled no; no-osd set video-zoom 0
r cycle-values video-rotate 270 180 90 0
s {image} cycle-values image-display-duration 1 inf; no-osd set video-zoom 0; no-osd set panscan 0; no-osd set video-unscaled no
t cycle-values video-rotate 90 180 270 0
u {image} no-osd cycle-values video-unscaled yes no; no-osd set video-zoom 0; no-osd set panscan 0
v cycle-values video-rotate 0 180