[addressbooks]
[[contacts]]
path = ~/.local/share/contacts/private

[contact table]
display = formatted_name
show_uids = no
show_kinds = yes
sort = formatted_name
localize_dates = no

[vcard]
preferred_version = 4.0
