#!/usr/bin/env bash

# Environment variables
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export EDITOR=${EDITOR:-hx}

source "$XDG_CONFIG_HOME/user-dirs.dirs"

# Atuin init
# Install atuin hook if all:
#  - shell is interactive
#  - atuin command is present
#  - atuin is configured
if [ -n "$PS1" ] && \
	command -v atuin 2>/dev/null 1>&2 && \
	[[ -f "$XGD_CONFIG_HOME/atuin/config.toml" ]]; then
	eval "$(atuin init bash --disable-up-arrow)"
fi


# Starship init
# Install starship hook if all:
#  - shell is interactive
#  - terminal is not dumb
#  - starship is available
#  - starship config exists
if [ -n "$PS1" ] && \
	[[ $TERM != "dumb" ]] && \
	command -v starship 2>/dev/null 1>&2 && \
	[[ -f "$XDG_CONFIG_HOME/starship.toml" ]]; then
	eval "$(starship init bash)"
fi
