#!/usr/bin/env bash

export __BASHRC_SOURCED=1

prepend_path() {
	case ":$PATH:" in
	*:"$1":*) ;;
	*) PATH="$1:$PATH" ;;
	esac
}

#
# Run fish shell
# If parent shell is not shell,
# if execution string not set (like bash -c),
# if shell level 1,
# if fish command is present
# Pass login option to fish shell
#
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]] &&
	command -v fish 2>/dev/null 1>&2; then
	shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
	exec fish "$LOGIN_OPTION"
fi

#
# Environment variables
#
prepend_path "$HOME/.local/bin"

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export EDITOR=${EDITOR:-hx}

# shellcheck source=.config/user-dirs.dirs
source "$XDG_CONFIG_HOME/user-dirs.dirs"

# fzf init
# Install fzf hoot if all:
#  - shell is interactive
#  - fzf command is present
if [ -n "$PS1" ] &&
	command -v fzf 2>/dev/null 1>&2; then
	eval "$(fzf --bash)"
fi

# Atuin init
# Install atuin hook if all:
#  - shell is interactive
#  - atuin command is present
#  - atuin is configured
if [ -n "$PS1" ] &&
	command -v atuin 2>/dev/null 1>&2 &&
	[[ -f "$XDG_CONFIG_HOME/atuin/config.toml" ]]; then
	eval "$(atuin init bash --disable-up-arrow --disable-ctrl-r)"
fi

# Starship init
# Install starship hook if all:
#  - shell is interactive
#  - terminal is not dumb
#  - starship is available
#  - starship config exists
if [ -n "$PS1" ] &&
	[[ $TERM != "dumb" ]] &&
	command -v starship 2>/dev/null 1>&2 &&
	[[ -f "$XDG_CONFIG_HOME/starship.toml" ]]; then
	eval "$(starship init bash)"
fi
