theme = "darcula"

[editor]
line-number = "relative"
bufferline = "multiple"
# trim-final-newlines = true
# trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎"  # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = " "
mode.insert = "↪"
mode.select = "⇕"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

# lazygit integration
[keys.normal]
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]

# TODO: yazi integration
# TODO: scooter integration
