[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }
fish-lsp = { command = "fish-lsp", args = [
  "start",
], environment = { fish_lsp_show_client_popups = "false" } }
just-lsp = { command = "just-lsp" }
systemd-lsp = { command = "systemd-lsp" }
ty = { command = "ty", args = ["server"] }

[[language]]
name = "awk"
formatter = { command = "awk", timeout = 5, args = [
  "--file=/dev/stdin",
  "--pretty-print=/dev/stdout",
] }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "shfmt", args = ["-s", "-i", "2"] }

[[language]]
name = "css"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.css"
] }
language-servers = ["biome", "vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "dockerfile"
formatter = { command = "dprint", args = ["fmt", "--stdin", "dockerfile"] }

[[language]]
name = "docker-compose"
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }

[[language]]
name = "fish"
language-servers = ["fish-lsp"]

[[language]]
name = "graphql"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.graphql"
] }
language-servers = ["biome"]

[[language]]
name = "hcl"
formatter = { command = "terraform", args = ["fmt", "-"] }

[[language]]
name = "html"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.html"
] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "biome"]

[[language]]
name = "javascript"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.js"
] }
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome"
]

[[language]]
name = "jsx"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.jsx"
] }
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome"
]

[[language]]
name = "json"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.json"
] }
language-servers = ["vscode-json-language-server", "biome"]

[[language]]
name = "jsonc"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.jsonc"
] }
language-servers = ["vscode-json-language-server", "biome"]

[[language]]
name = "jsonc"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.jsonc"
] }
language-servers = ["vscode-json-language-server", "biome"]

[[language]]
name = "just"
formatter = { command = "just", args = ["--justfile", "/dev/stdin", "--dump"] }
language-servers = ["just-lsp"]

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["basedpyright", "ruff", "ty"]
rulers = [88]

[[language]]
name = "scss"
formatter = { command = "dprint", args = ["fmt", "--stdin", "malva"] }

[[language]]
name = "systemd"
scope = "source.ini"
file-types = [
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "nspawn",
  "path",
  "scope",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  { glob = "systemd/**/*.conf" },
]
injection-regex = "systemd"
comment-token = "#"
grammar = "ini"
language-servers = ["systemd-lsp"]

[[language]]
name = "svelte"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.json"
] }
language-servers = ["svelteserver", "tailwindcss-ls", "biome"]

[[language]]
name = "tfvars"
formatter = { command = "terraform", args = ["fmt", "-"] }

[[language]]
name = "toml"
language-servers = ["tombi", "taplo"]

[[language]]
name = "typescript"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.ts"
] }
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome"
]

[[language]]
name = "tsx"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.tsx"
] }
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "tailwindcss-ls",
  "biome"
]

[[language]]
name = "vue"
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "buffer.vue"
] }
language-servers = ["biome"]
