# mise completes terramate from the packslip of whichever version is active.
# @generated by usage's installer for `mise completion fish --tool terramate --install`
# The vendor's script is read in a child shell, once per completion, so its
# registrations and helper functions never outlive the version they came
# from and a version switch in another directory is followed at the next tab.
function __mise_load_terramate
    set -l __mise_fish (status fish-path)
    set -l __mise_line (commandline --current-process --cut-at-cursor | string collect --allow-empty)
    # An empty completion path keeps the child from autoloading this stub.
    $__mise_fish --no-config -c '
        set fish_complete_path
        command mise completion fish --tool $argv[1] 2>/dev/null | source
        complete --do-complete "$argv[2]"
    ' -- 'terramate' $__mise_line
end
complete -c 'terramate' -f -a '(__mise_load_terramate)'
