minimumLimaVersion: 1.0.1

mountTypesUnsupported: ["9p"]
mountInotify: true
mounts:
  - location: "~/.local/share/chezmoi"

containerd:
  system: false
  user: false

user:
  home: "/home/{{.User}}"

ssh:
  loadDotSSHPubKeys: true

networks:
  - lima: user-v2

upgradePackages: true

hostResolver:
  enabled: true
  # hosts:
  #   guest.name: 127.1.1.1
  #   host.name: host.lima.internal

provision:
  # fix permissions
  - mode: system
    script: |
      #!/usr/bin/env bash
      set -eux -o pipefail
      mkdir -p {{.Home}}/bin
      mkdir -p {{.Home}}/.local/share
      chown {{.User}}:{{.User}} \
        {{.Home}}/bin \
        {{.Home}}/.local \
        {{.Home}}/.local/share

  # apply dotfiles
  - mode: user
    script: |
      #!/usr/bin/env bash
      set -eux -o pipefail
      WORKDIR=~/.local/share/chezmoi
      if [ ! -d "$WORKDIR/.git" ]; then sleep 10; fi
      which chezmoi || sh $WORKDIR/bin/install-chezmoi-bin -b ~/bin
      ~/bin/chezmoi init --apply
