minimumLimaVersion: 1.0.7

# NOTE: 9p is broken in Linux v6.9, v6.10, and v6.11
mountTypesUnsupported: ["9p"]
mountInotify: true
mounts:
  - location: "~/.local/share/chezmoi"
    mountPoint: "{{.Home}}/.local/share/chezmoi"
    writable: true

containerd:
  system: false
  user: false

user:
  name: lima
  home: "/home/{{.User}}"
  shell: "/bin/bash"

ssh:
  loadDotSSHPubKeys: true

networks:
  - lima: user-v2

upgradePackages: true

hostResolver:
  enabled: true
  # hosts:
  #   guest.name: 127.1.1.1
  #   host.name: host.lima.internal

provision:
  - mode: user
    script: |
      #!/usr/bin/env bash
      set -eux -o pipefail
      which chezmoi || sh -c "$(curl -fsLS get.chezmoi.io)"
      chezmoi init --apply
